Fix NoSuchMethodError by adding kotlin-reflect to Java dependencies
- Added `kotlin-reflect` to the `pom.xml` as it was missing and `Builders.kt` in `jvm-libp2p` was crashing on startup calling `kotlin.jvm.internal.MutablePropertyReference1Impl.<init>`.
- Reverted kotlin version from `1.8.20` back to original `1.9.22` as it is not the actual cause.

Co-authored-by: autonull <157093+autonull@users.noreply.github.com>